[workspace]
changelog_update = true
git_tag_enable = true
git_tag_name = "v{{ version }}"
git_release_enable = true
publish = false

[[package]]
name = "djv"
changelog_include = ["feat", "fix", "perf", "refactor", "docs"]
features_always_increment_minor = true
